using StockLite.Models;
using StockLite.Services;
using System;
using System.Linq;
using System.Windows.Forms;

namespace StockLite
{
    public partial class FrmProducto : Form
    {
        private Producto? seleccionado = null;

        public FrmProducto()
        {
            InitializeComponent();
            ConfigurarGrid();
            CargarCategoriasCombo();
            CargarComboFiltroCategoria();
            CargarProveedoresCombo();
            CargarComboFiltroProveedor();
            CargarProductos();
            this.StartPosition = FormStartPosition.CenterScreen;

            txtCodigo.ReadOnly = true;
            txtCodigo.BackColor = Color.LightGray;
            txtCodigo.Text = "AutoGenerated";
        }

        private void ConfigurarGrid()
        {
            dgvProductos.AutoGenerateColumns = false;
            dgvProductos.Columns.Clear();
            dgvProductos.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "ProductoId", HeaderText = "ID", Width = 60 });
            dgvProductos.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "Codigo", HeaderText = "Código", Width = 90 });
            dgvProductos.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "Nombre", HeaderText = "Producto", Width = 150 });
            dgvProductos.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "CategoriaNombre", HeaderText = "Categoría", Width = 130 });
            dgvProductos.Columns.Add(new DataGridViewTextBoxColumn {DataPropertyName = "ProveedorNombre",HeaderText = "Proveedor",Width = 130});
            dgvProductos.Columns.Add(new DataGridViewTextBoxColumn
            {
                DataPropertyName = "PrecioCosto",
                HeaderText = "Costo",
                Width = 80,
                DefaultCellStyle = new DataGridViewCellStyle { Format = "N2" }
            });
            dgvProductos.Columns.Add(new DataGridViewTextBoxColumn
            {
                DataPropertyName = "PrecioVenta",
                HeaderText = "Precio Venta",
                Width = 80,
                DefaultCellStyle = new DataGridViewCellStyle { Format = "N2" }
            });
            dgvProductos.Columns.Add(new DataGridViewTextBoxColumn
            {
                DataPropertyName = "StockActual",
                HeaderText = "Stock",
                Width = 80
            });

           


            dgvProductos.ReadOnly = true;
            dgvProductos.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvProductos.AllowUserToAddRows = false;
            dgvProductos.CellClick += dgvProductos_CellClick;

            dgvProductos.RowHeadersVisible = false;
            dgvProductos.RowHeadersWidth = 4;
            dgvProductos.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        }

        private void CargarProductos()
        {
            string texto = txtBuscar.Text.Trim();
            int? categoriaId = cmbCategoriaFiltro.SelectedValue as int?;
            var lista = ProductoService.GetAll();
            int proveedorId = (cmbProveedorFiltro.SelectedValue is int pv) ? pv : 0;


            if (!string.IsNullOrEmpty(texto))
                lista = lista.Where(p => p.Codigo.Contains(texto, StringComparison.OrdinalIgnoreCase) ||
                                        p.Nombre.Contains(texto, StringComparison.OrdinalIgnoreCase)).ToList();

            if (categoriaId.HasValue && categoriaId.Value > 0)
                lista = lista.Where(p => p.CategoriaId == categoriaId.Value).ToList();

            if (proveedorId > 0)
                lista = lista.Where(p => p.ProveedorId == proveedorId).ToList();

            dgvProductos.DataSource = null;
            dgvProductos.DataSource = lista;

            if (dgvProductos.Rows.Count > 0)
            {
                dgvProductos.Rows[0].Selected = true;
                MostrarProductoSeleccionado();
            }
            else
            {
                Limpiar();
            }
        }

        private void CargarCategoriasCombo()
        {
            var categorias = CategoriaService.GetAll();
            cmbCategoria.DataSource = categorias;
            cmbCategoria.DisplayMember = "Nombre";
            cmbCategoria.ValueMember = "CategoriaId";
            cmbCategoria.SelectedIndex = -1;
        }

        private void CargarComboFiltroCategoria()
        {
            var categorias = CategoriaService.GetAll();
            cmbCategoriaFiltro.DataSource = categorias;
            cmbCategoriaFiltro.DisplayMember = "Nombre";
            cmbCategoriaFiltro.ValueMember = "CategoriaId";
            cmbCategoriaFiltro.SelectedIndex = -1;
            cmbCategoriaFiltro.Text = "Filtrar por categoría";
        }

        private void CargarComboFiltroProveedor()
        {
            var proveedores = ProveedorService.GetAll();
            cmbProveedorFiltro.DataSource = proveedores;
            cmbProveedorFiltro.DisplayMember = "Nombre";
            cmbProveedorFiltro.ValueMember = "ProveedorId";
            cmbProveedorFiltro.SelectedValue = 0;
            cmbCategoriaFiltro.Text = "Filtrar por proveedor";
        }


        private void CargarProveedoresCombo()
        {
            var proveedores = ProveedorService.GetAll();

            cmbProveedor.DataSource = proveedores;
            cmbProveedor.DisplayMember = "Nombre";
            cmbProveedor.ValueMember = "ProveedorId";
            cmbProveedor.SelectedValue = 0;
        }

        private void Limpiar()
        {
            txtCodigo.Text = "AutoGenerated";
            txtNombre.Clear();
            txtCosto.Clear();
            txtVenta.Clear();
            cmbCategoria.SelectedIndex = -1;
            cmbProveedor.SelectedIndex = -1;
            seleccionado = null;
            btnGuardar.Text = "Guardar";
            txtNombre.Focus();
        }

        private void MostrarProductoSeleccionado()
        {
            if (dgvProductos.CurrentRow?.DataBoundItem is Producto p)
            {
                seleccionado = p;
                txtCodigo.Text = p.Codigo;
                txtNombre.Text = p.Nombre;
                txtCosto.Text = p.PrecioCosto.ToString("N2");
                txtVenta.Text = p.PrecioVenta.ToString("N2");
                cmbCategoria.SelectedValue = p.CategoriaId;
                cmbProveedor.SelectedValue = p.ProveedorId.HasValue ? p.ProveedorId.Value : 0;
                btnGuardar.Text = "Actualizar";

            }
        }

        private void dgvProductos_CellClick(object? sender, DataGridViewCellEventArgs e)
        {
            if (e.RowIndex >= 0) MostrarProductoSeleccionado();
        }

        private void btnNuevo_Click(object sender, EventArgs e) => Limpiar();

        private void btnGuardar_Click(object sender, EventArgs e)
        {
            if (string.IsNullOrWhiteSpace(txtNombre.Text) ||
                cmbCategoria.SelectedValue == null ||
                !decimal.TryParse(txtCosto.Text, out decimal costoActual) ||
                !decimal.TryParse(txtVenta.Text, out decimal precio))
            {
                MessageBox.Show("Complete todos los campos correctamente e ingrese valores numéricos válidos.",
                    "Validación", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                return;
            }

            try
            {
                int usuarioId = FormMainMenu.UsuarioActual?.UsuarioId ?? 1;
                int catId = (int)cmbCategoria.SelectedValue;
                string nombre = txtNombre.Text.Trim();
                int proveedorId = (int)cmbProveedor.SelectedValue;
                int? proveedorIdNullable = proveedorId == 0 ? null : proveedorId;

                if (seleccionado == null)
                {
                    string codigoGenerado = ProductoService.ObtenerSiguienteCodigo();
                    ProductoService.Insert(
                        codigoGenerado,
                        nombre,
                        catId,
                        costoActual,
                        precio,
                        proveedorIdNullable);  

                    MessageBox.Show($"Producto creado correctamente.\nCódigo: {codigoGenerado}\nCosto: {costoActual:N2}\nPrecio: {precio:N2}",
                        "Éxito", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
                else
                {
                    ProductoService.Update(
                        seleccionado.ProductoId,
                        seleccionado.Codigo,
                        nombre,
                        catId,
                        costoActual,
                        precio,
                        proveedorIdNullable,   
                        usuarioId);

                    MessageBox.Show("Producto actualizado correctamente.", "Éxito", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }

                CargarProductos();
                Limpiar();
            }
            catch (Exception ex)
            {
                MessageBox.Show("Error: " + ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }

        private void btnEliminar_Click(object sender, EventArgs e)
        {
            if (seleccionado == null) return;
            if (MessageBox.Show($"¿Eliminar el producto '{seleccionado.Nombre}'?", "Confirmar", MessageBoxButtons.YesNo, MessageBoxIcon.Question) == DialogResult.Yes)
            {
                ProductoService.Delete(seleccionado.ProductoId);
                CargarProductos();
                Limpiar();
            }
        }

        private void btnLimpiarBusqueda_Click(object sender, EventArgs e)
        {
            txtBuscar.Clear();
            cmbCategoriaFiltro.SelectedIndex = -1;
            cmbCategoriaFiltro.Text = "Filtrar por categoría";
            cmbProveedorFiltro.SelectedIndex = -1;
            cmbProveedorFiltro.Text = "Filtrar por proveedor";
            txtBuscar.Focus();
        }

        private void btnCancelar_Click(object sender, EventArgs e) => Limpiar();

        private void txtBuscar_TextChanged(object sender, EventArgs e) => CargarProductos();
        private void cmbCategoriaFiltro_SelectionChangeCommitted(object sender, EventArgs e) => CargarProductos();

        private void cmbProveedorFiltro_SelectionChangeCommitted(object sender, EventArgs e)
        {
            CargarProductos();
        }


    }
}